### ISSUE TITLE
Logo Request

### ISSUE THREAD

**Issue by tjulises** [karinakozarova/Arduino-Dancer#5]
Greetings @karinakozarova ,

I've taken a look at yout project and yes, I'm interested in collaborating in it!

It would be my pleasure, before starting with the logo-making procedure I'll like to get some pictures of the characters, all tho your wiki describes the game very well, it would be easier to have as **much** info so this logo **transmit** what it's meant to.

I'll be waiting for your feedback!

**Comment by karinakozarova** [comment]
Hey, @tjulises we don't really have characters. 

It's simply falling arrows. For a short demo you can watch https://www.youtube.com/watch?v=yn1DPOFjluQ&feature=youtu.be. The main part of the game is between 0:30-0:50. That's the whole concept.

 Soon we will also add support for playing the game using a [dance pad](https://www.google.com/search?q=dance+pad&client=ubuntu&hs=8a&channel=fs&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiB3-O8k7zbAhUJXRQKHVdnC6QQ_AUICigB&biw=1280&bih=582#imgrc=STzKWdK8KwZ73M:), controlled by Arduino microcontroller. I think that's the main part that should be embedded into the logo along with the arrows but I live all of what should be into the logo up to you! 

Thanks for your interest in collaborating, it's a pleasure.

**Comment by tjulises** [comment]
Ok, Ive seen the content, this is what I came up with, doesn't mean I can't change it if you dont like it, if you like something please tell me which one and if needs some/any adjustment. Hope you like it.

![arduino logov](https://user-images.githubusercontent.com/39039587/41167204-4312606c-6b10-11e8-8753-93fa7d6ac451.jpg)

**Comment by karinakozarova** [comment]
Oh, wow, I'm simply amazed with the quality of your work, congratulations! :tada:  This has been a very hard choice but after a lot of thought, that's what I've decided:

From the **icons** I believe that the last one, the most colourful is the right choice for us. I think those icons could actually be also used ingame, not as logo but as the arrows that have to be hit so we would greatly appreciate it if we can use them too.

From the **icon variants**, the first one is the most appropriate for our game.

From the **Icons + Fonts**, I can't choose between 2 logos - the first on the second row and the second on the second row. However, I have a little request - for the second on the second row if you can make the "dancer" to use the same font as the "arduino" would be perfect and also, if you can make the "dancer" in the first on the second row to be coloured blue and the blue arrow to become green.

It will be great if besides the Pull Request you will make with our selected versions, you give us a link to all those versions in a file format you think will be okay(preferably .psd + .png) because we would like to embed your awesome logos into our game.

Also, to give you the credits I think you deserve, I would like to add you to the credits of our game - can you tell me what you would like for us to write about you in them?

Finally, I really enjoy the way you designed our logo and I hope we can collaborate again in the future!

**Comment by tjulises** [comment]
Ok I'll start making the adjustments, I'm glad you liked it, as for the credits, I'll leave it up to you, it would be really cool just to be mentioned in the readme with an hyperlink to my profile.

if I provide an .svg file format it would be enough or it has to be specifically .psd? @karinakozarova

**Comment by karinakozarova** [comment]
Besides being mentioned in the readme, we would also add your credits to the end of the game. We will link your GitHub profile but if you want we can also link something else?

.svg, .png, pdf and cdr would be enough.

**Comment by karinakozarova** [comment]
Hey, @tjulises, I'd like to use 2, 4, 6, 7, 9.

The colours are awesome, thanks!

**Comment by tjulises** [comment]
ok, so the arrows are gonna be used for the game and the typography its gonna be used as the logo of the game?

where could I submit the files, in source repo or just the readme? and as I said before Ill upload a google drive link too.

I'll wait for the feedback to make the pull request :+1: 

@karinakozarova

**Comment by karinakozarova** [comment]
How about to the ReadMe(with all links you ant to your profiles) the logo and the designs to a folder Designs in docs with another .md file about you?

**Comment by tjulises** [comment]
I've made the [pull request](#6) now, thanks :+1: 

@karinakozarova

**Comment by karinakozarova** [comment]
Merged #6
